Exception in thread "main" java.lang.ArrayIndexOutOfBoundsException: 0
	at Human.main(Human.java:161)
